"""
Generalised workflow for constructing wake-resolved TurbSim inflow files
for OpenFAST using PyWake or LES-informed target fields.

This script was developed for the AERO43520 Advanced Research Project:
"Predicting Fatigue Loads of Offshore Wind Turbines Operating in Upstream Wakes".

This script takes baseline TurbSim .bts files generated by the user, samples a
wake field from PyWake at the selected turbine inflow plane, and writes new
wake-resolved .bts files for OpenFAST.

Workflow
--------
1. Generate baseline TurbSim .bts files separately.
2. Define the wind farm layout.
3. Use the original custom_functions.py file to create the turbine, site and
   PyWake wake model.
4. Sample PyWake mean velocity and turbulence intensity on the TurbSim grid.
5. Decompose the baseline TurbSim field into mean and fluctuating components.
6. Replace the mean field with the PyWake wake field.
7. Scale the fluctuations to match the PyWake turbulence intensity field.
8. Save the reconstructed waked .bts file.


Notes
-----
- The script assumes that the baseline TurbSim files already contain realistic
  stochastic turbulence, shear and time variation.
- Wake reconstruction is performed by decomposing the streamwise TurbSim field
  into a mean component and fluctuating component:

      U(t, y, z) = U_mean(y, z) + u'(t, y, z)

  The mean velocity is replaced/scaled using a target wake field, while the
  fluctuations are scaled to match a target turbulence intensity field.
- The default turbine data correspond to the IEA 15 MW reference turbine.
- The default turbine data is also preset to the input conditions considered in 
  accompanying technical report, which the USER needs to change for their own
  conditions.

- The PyWake simulation is set up in accordance to the documentation:
   requiring a turbine, farm and site definition.

Required packages
-----------------
numpy, pandas, matplotlib, scipy, pathlib
py_wake
pyFAST or openfast_toolbox for reading/writing TurbSim .bts files
TurbSim and OpenFAST tool kit envinronments, in order to use the resolved files 


A custom functions file created by PDRA Diego Aray is also provided, 
which is needed in order to correctly implement the various engineering 
wake models correctly.

Edit the file paths in the USER INPUTS section before running.
Author
------
Ahmed Danayal
University of Manchester

Special thanks to Diego Araya
"""
#%%
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.interpolate import RegularGridInterpolator

from py_wake.wind_turbines import WindTurbine, WindTurbines
from py_wake.wind_turbines.power_ct_functions import PowerCtTabular
from py_wake.site.xrsite import UniformSite
from py_wake.site.shear import PowerShear
from py_wake.flow_map import YZGrid

# PyWake literature models
from py_wake.literature.gaussian_models import (
    Bastankhah_PorteAgel_2014,
    Niayifar_PorteAgel_2016,
)
from py_wake.literature.turbopark import Nygaard_2022

# TurbSim .bts I/O.
# If this import fails, check whether your environment uses:
#   from openfast_toolbox.io import TurbSimFile
from pyFAST.input_output import TurbSimFile

# Custom functions input file, developed by PDRA Diego Araya. 
from custom_functions import (
    get_wind_turbines,
    get_uniform_site,
    setup_wind_farm_model,
)
#%%

# -----------------------------------------------------------------------------
# USER CONFIGURATION
# -----------------------------------------------------------------------------

@dataclass
class WorkflowConfig:
    """User inputs for the PyWake-to-TurbSim superposition workflow."""

    # Folder containing baseline TurbSim files generated by the user.
    baseline_bts_dir: Path = Path(
        r"D:\OpenFAST\15MW\cases\Validate_Final\New_NTM_PDBL\TurbSim"
    )
    # Naming pattern for baseline TurbSim files.
    # Example: "15MW_U10_S{seed}.bts" with seeds = (101, 102, ...)
    baseline_bts_pattern: str = "15MW_U10_S{seed}.bts"

    # Output folder for reconstructed waked .bts files.
    output_root: Path = Path(r"D:\OpenFAST\PyWake")

    # Selected turbine number in the farm layout. T1 corresponds to index 0.
    turbine_number: int = 120

    # Farm/turbine geometry.
    # These should match the turbine and TurbSim setup used in your case.
    rotor_diameter: float = 240.0
    hub_height: float = 150.0
    n_rows: int = 16
    n_cols: int = 16
    streamwise_spacing_D: float = 7.5
    crossflow_spacing_D: float = 7.5
    farm_rotation_deg: float = -30.0 # Remove if considering a non-rotated farm.

    # PyWake inflow conditions.
    ambient_wind_speed: float = 10.0
    ambient_ti: float = 0.061
    wind_direction_deg: float = 270.0
    shear_alpha: float = 0.1

    # Sampling plane location upstream of the selected turbine.
    upstream_sampling_distance_D: float = 1.0

    # TurbSim seeds to process.
    seeds: Tuple[int, ...] = (107,)

    # Model names must match those implemented in custom_functions.py.
    models: Tuple[str, ...] = (
        "BPA2014",
        "NPA2016",
        "Nygaard2022",
        "Nygaard2022_A0.06",
    )

    # If True, do not reduce local TI below the baseline TurbSim value.
    avoid_reducing_ti: bool = True

    # Optional plotting switches.
    plot_layout: bool = True
    plot_full_pywake_plane: bool = True
    plot_sampled_field: bool = False


# =============================================================================
# FARM LAYOUT
# =============================================================================

def build_rotated_grid_layout(
    n_rows: int,
    n_cols: int,
    spacing_x_m: float,
    spacing_y_m: float,
    rotation_deg: float,
) -> Tuple[np.ndarray, np.ndarray]:
    """
    Build a rectangular wind farm layout and rotate it about the origin.

    Turbine numbering follows row-major ordering:
    T1, T2, ..., Tn.
    """

    x, y = [], []

    for row in range(n_rows):
        for col in range(n_cols):
            x.append(row * spacing_x_m)
            y.append(col * spacing_y_m)

    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)

    theta = np.deg2rad(rotation_deg)
    x_rot = x * np.cos(theta) - y * np.sin(theta)
    y_rot = x * np.sin(theta) + y * np.cos(theta)

    return x_rot, y_rot


def plot_farm_layout(x: np.ndarray, y: np.ndarray, title: str = "Wind farm layout") -> None:
    """Plot turbine locations as a quick layout check."""

    fig, ax = plt.subplots(figsize=(8, 8))
    ax.scatter(x, y, s=20)

    for i, (xi, yi) in enumerate(zip(x, y), start=1):
        ax.text(xi + 20, yi + 20, f"T{i}", fontsize=6)

    ax.set_xlabel("x [m]")
    ax.set_ylabel("y [m]")
    ax.set_title(title)
    ax.axis("equal")
    ax.grid(True)
    fig.tight_layout()
    plt.show()


# =============================================================================
# PYWAKE TURBINE AND SITE SETUP
# =============================================================================

def create_iea_15mw_wind_turbines() -> WindTurbines:
    """
    Create the 15 MW turbine definition used by the original workflow.

    The wake model itself is still created using setup_wind_farm_model from the
    original custom_functions.py file. This function only defines the turbine
    object so that the geometry is consistent with the TurbSim/OpenFAST case.
    """

    wind_speeds = np.arange(3, 26)

    power_15mw_kw = np.array([
        70.021377, 595.088475, 1429.216889, 2656.263808, 4339.296326,
        6481.116995, 9229.227024, 12661.25448, 14994.26629, 14994.17331,
        14994.76256, 14994.76121, 14994.75771, 14994.75771, 14994.75771,
        14994.82665, 14994.82665, 14994.82754, 14995.0, 14996.27008,
        14996.27008, 14996.27008, 14997.62687,
    ])

    ct_15mw = np.array([
        0.819748943, 0.808268424, 0.823265981, 0.834932456, 0.806651158,
        0.804571567, 0.803904895, 0.80345211, 0.607277698, 0.425965654,
        0.32116631, 0.2511023, 0.201415182, 0.201415182, 0.201415182,
        0.125653944, 0.125653944, 0.08506697, 0.08506697, 0.061026446,
        0.061026446, 0.061026446, 0.045814967,
    ])

    turbine = WindTurbine(
        name="15MW",
        diameter=240.0,
        hub_height=150.0,
        powerCtFunction=PowerCtTabular(wind_speeds, power_15mw_kw, "kW", ct_15mw),
    )

    return WindTurbines.from_WindTurbine_lst([turbine])


def create_pywake_site(
    ambient_wind_speed: float,
    ambient_ti: float,
    hub_height: float,
    shear_alpha: float,
) -> UniformSite:
    """Create the PyWake site used by the original workflow, including power-law shear."""

    return UniformSite(
        p_wd=[1.0],
        ti=ambient_ti,
        ws=[ambient_wind_speed],
        shear=PowerShear(h_ref=hub_height, alpha=shear_alpha),
    )


# =============================================================================
# PYWAKE SAMPLING
# =============================================================================

def run_pywake_models(
    model_names: Iterable[str],
    site,
    wind_turbines,
    x: np.ndarray,
    y: np.ndarray,
    wind_direction_deg: float,
    wind_speed: float,
) -> Dict[str, object]:
    """Run each requested PyWake model using the original custom setup function."""

    outputs: Dict[str, object] = {}

    for model_name in model_names:
        print(f"Running PyWake model: {model_name}")

        wind_farm_model = setup_wind_farm_model(
            site=site,
            wind_turbines=wind_turbines,
            model=model_name,
        )

        outputs[model_name] = wind_farm_model(
            x=x,
            y=y,
            wd=np.asarray([wind_direction_deg]),
            ws=np.asarray([wind_speed]),
        )

    return outputs


def extract_pywake_yz_fields(
    sim_res,
    x_probe: float,
    y_abs: np.ndarray,
    z_abs: np.ndarray,
) -> Tuple[np.ndarray, np.ndarray]:
    """
    Sample PyWake mean velocity and turbulence intensity on a Y-Z plane.

    Returns
    -------
    U_target, TI_target:
        Arrays in TurbSim grid order with shape (ny, nz).
    """

    flow = sim_res.flow_box(
        x=np.asarray([x_probe]),
        y=y_abs,
        h=z_abs,
    )

    U_target = np.asarray(flow.WS_eff.squeeze().values)
    TI_target = np.asarray(flow.TI_eff.squeeze().values)

    # PyWake versions can return either (ny, nz) or (nz, ny).
    if U_target.shape == (len(z_abs), len(y_abs)):
        U_target = U_target.T
        TI_target = TI_target.T

    expected_shape = (len(y_abs), len(z_abs))
    if U_target.shape != expected_shape:
        raise ValueError(
            f"Unexpected PyWake field shape. Expected {expected_shape}, "
            f"got {U_target.shape}."
        )

    return U_target, TI_target

def plot_pywake_sampled_plane(
    sim_res,
    x_probe: float,
    y_centre: float,
    y_ts: np.ndarray,
    z_ts: np.ndarray,
    hub_height: float,
    rotor_diameter: float,
    title: str = "PyWake sampled rotor plane",
) -> None:
    """
    Plot the PyWake velocity field sampled on the TurbSim rotor grid.

    This is the exact rotor-specific target field that is superposed onto the
    baseline TurbSim .bts file.
    """

    y_abs = y_centre + y_ts

    U_target, TI_target = extract_pywake_yz_fields(
        sim_res=sim_res,
        x_probe=x_probe,
        y_abs=y_abs,
        z_abs=z_ts,
    )

    Y, Z = np.meshgrid(y_ts / rotor_diameter, z_ts / rotor_diameter, indexing="ij")

    fig, ax = plt.subplots(figsize=(7, 5), constrained_layout=True)

    c0 = ax.contourf(Y, Z, U_target, levels=40, cmap="viridis")

    ax.axvline(0.0, color="white", linestyle="--", lw=0.7, alpha=0.8)
    ax.axhline(hub_height / rotor_diameter, color="white", linestyle="--", lw=0.7, alpha=0.8)

    rotor_circle = plt.Circle(
        (0.0, hub_height / rotor_diameter),
        0.5,
        fill=False,
        edgecolor="white",
        linewidth=1.6,
    )
    ax.add_patch(rotor_circle)

    ax.set_xlabel(r"$y/D$")
    ax.set_ylabel(r"$z/D$")
    ax.set_title(title)
    ax.set_aspect("equal", adjustable="box")
    ax.invert_xaxis()

    cbar = fig.colorbar(c0, ax=ax, shrink=0.9, pad=0.025)
    cbar.set_label(r"$\overline{U}$ [m s$^{-1}$]")

    plt.show()

    print(f"Rotor-sampled U_target min/max:  {np.nanmin(U_target):.3f}, {np.nanmax(U_target):.3f}")
    print(f"Rotor-sampled TI_target min/max: {np.nanmin(TI_target):.4f}, {np.nanmax(TI_target):.4f}")


def find_upstream_turbines_for_yz_plane(
    x: np.ndarray,
    y: np.ndarray,
    target_index: int,
    rotor_diameter: float,
    y_extent_D: float = 1.5,
    max_turbines: int = 2,
) -> np.ndarray:
    """
    Identify upstream turbine projections that fall within the plotted Y-Z plane.

    This follows the original plotting logic: for WD=270 deg, the flow is treated
    as travelling in the +x direction, so upstream turbines have dx < 0 relative
    to the selected turbine.
    """

    x_centre = x[target_index]
    y_centre = y[target_index]

    dx_D = (x - x_centre) / rotor_diameter
    dy_D = (y - y_centre) / rotor_diameter

    mask = (dx_D < 0.0) & (np.abs(dy_D) <= y_extent_D)
    candidate_indices = np.where(mask)[0]

    if candidate_indices.size == 0:
        return candidate_indices

    candidate_indices = candidate_indices[np.argsort(np.abs(dx_D[candidate_indices]))]
    return candidate_indices[:max_turbines]


def plot_full_pywake_yz_plane(
    sim_res,
    x_probe: float,
    y_centre: float,
    x_layout: np.ndarray,
    y_layout: np.ndarray,
    target_index: int,
    rotor_diameter: float,
    hub_height: float,
    model_name: str,
    turbine_number: int,
    y_extent_D: float = 1.5,
    z_min_D: float = 0.1,
    z_max_D: float = 2.05,
    n_y: int = 220,
    n_z: int = 180,
) -> None:
    """
    Plot a report-style PyWake Y-Z plane around the selected turbine.

    This is for visual checking only. The .bts file is still reconstructed using
    the rotor-specific TurbSim grid sampled separately inside write_pywake_superposed_bts().
    """

    D = rotor_diameter
    R = D / 2.0

    # Match the original report convention: positive y/D plotted to the left.
    y_rel_D = np.linspace(-y_extent_D, y_extent_D, n_y)
    z_D = np.linspace(z_min_D, z_max_D, n_z)

    y_rel_m = y_rel_D * D
    z_abs = z_D * D
    y_abs = y_centre + y_rel_m

    U_field, TI_field = extract_pywake_yz_fields(
        sim_res=sim_res,
        x_probe=x_probe,
        y_abs=y_abs,
        z_abs=z_abs,
    )

    Y, Z = np.meshgrid(y_rel_D, z_D, indexing="ij")

    u_vmin = np.floor(np.nanmin(U_field) * 10.0) / 10.0
    u_vmax = np.ceil(np.nanmax(U_field) * 10.0) / 10.0
    u_levels = np.linspace(u_vmin, u_vmax, 40)

    fig, ax = plt.subplots(figsize=(7, 5), constrained_layout=True)

    c0 = ax.contourf(
        Y,
        Z,
        U_field,
        levels=u_levels,
        vmin=u_vmin,
        vmax=u_vmax,
        cmap="viridis",
    )

    ax.axvline(0.0, color="white", linestyle="--", lw=0.7, alpha=0.8)
    ax.axhline(hub_height / D, color="white", linestyle="--", lw=0.7, alpha=0.8)

    # Selected turbine rotor.
    selected_rotor = plt.Circle(
        (0.0, hub_height / D),
        R / D,
        fill=False,
        edgecolor="white",
        linewidth=1.8,
        zorder=5,
    )
    ax.add_patch(selected_rotor)

    # Project nearest upstream rotors into the same Y-Z plane.
    upstream_indices = find_upstream_turbines_for_yz_plane(
        x=x_layout,
        y=y_layout,
        target_index=target_index,
        rotor_diameter=D,
        y_extent_D=y_extent_D,
        max_turbines=2,
    )

    for idx in upstream_indices:
        yD_rel = (y_layout[idx] - y_centre) / D
        upstream_rotor = plt.Circle(
            (yD_rel, hub_height / D),
            R / D,
            fill=False,
            edgecolor="white",
            linestyle="--",
            linewidth=1.1,
            alpha=0.9,
            zorder=4,
        )
        ax.add_patch(upstream_rotor)
        ax.text(
            yD_rel,
            hub_height / D + R / D + 0.05,
            f"T{idx + 1}",
            color="white",
            fontsize=11,
            ha="center",
            va="bottom",
            zorder=6,
        )

    ax.set_xlabel(r"$y/D$")
    ax.set_ylabel(r"$z/D$")
    ax.set_title(rf"T{turbine_number}: {model_name} mean velocity, $x/D=-1$")
    ax.set_aspect("equal", adjustable="box")
    ax.grid(False)
    ax.invert_xaxis()

    cbar = fig.colorbar(c0, ax=ax, shrink=0.92, pad=0.025)
    cbar.set_label(r"$\overline{U}$ [m s$^{-1}$]")

    plt.show()

    rotor_mask = ((Y * D) ** 2 + (Z * D - hub_height) ** 2) <= R**2
    print(f"Full PyWake plane U min/max:  {np.nanmin(U_field):.3f}, {np.nanmax(U_field):.3f}")
    print(f"Rotor-region U mean:          {np.nanmean(U_field[rotor_mask]):.3f}")


# =============================================================================
# TURBSIM SUPERPOSITION
# =============================================================================

def superimpose_target_fields_on_turbsim(
    ts: TurbSimFile,
    U_target: np.ndarray,
    TI_target: np.ndarray,
    avoid_reducing_ti: bool = True,
    eps: float = 1e-6,
) -> TurbSimFile:
    """
    Replace the TurbSim mean velocity field and scale streamwise turbulence.

    The baseline TurbSim field is decomposed as:

        U(t, y, z) = Ubar(y, z) + u'(t, y, z)

    The mean field Ubar is replaced by the PyWake target velocity field, and
    the fluctuations are scaled so that the local standard deviation matches
    the target turbulence intensity.
    """

    velocity = ts["u"]
    u_streamwise = velocity[0]  # shape: (nt, ny, nz)

    expected_shape = u_streamwise.shape[1:]
    if U_target.shape != expected_shape:
        raise ValueError(
            f"Target field shape {U_target.shape} does not match TurbSim grid "
            f"shape {expected_shape}."
        )

    Ubar_original = np.mean(u_streamwise, axis=0)
    fluctuations = u_streamwise - Ubar_original[None, :, :]

    sigma_original = np.std(u_streamwise, axis=0)
    TI_original = sigma_original / np.maximum(Ubar_original, eps)

    if avoid_reducing_ti:
        TI_used = np.maximum(TI_target, TI_original)
    else:
        TI_used = TI_target

    sigma_target = TI_used * U_target
    scale = sigma_target / np.maximum(sigma_original, eps)

    u_rebuilt = U_target[None, :, :] + fluctuations * scale[None, :, :]

    if not np.isfinite(u_rebuilt).all():
        raise ValueError("Non-finite values detected in reconstructed velocity field.")

    velocity[0, :, :, :] = u_rebuilt
    ts["u"] = velocity

    return ts


def write_pywake_superposed_bts(
    config: WorkflowConfig,
    sim_res,
    model_name: str,
    x_probe: float,
    y_centre: float,
) -> None:
    """Apply PyWake target fields to each baseline TurbSim file."""

    out_dir = config.output_root / f"T{config.turbine_number}" / "TurbSim" / model_name
    out_dir.mkdir(parents=True, exist_ok=True)

    for seed in config.seeds:
        ts_file = config.baseline_bts_dir / config.baseline_bts_pattern.format(seed=seed)

        if not ts_file.exists():
            raise FileNotFoundError(f"Baseline TurbSim file not found: {ts_file}")

        print(f"Processing model={model_name}, seed={seed}")
        ts = TurbSimFile(str(ts_file))

        y_ts = np.asarray(ts["y"])
        z_ts = np.asarray(ts["z"])

        # TurbSim y-coordinates are relative to the sampled turbine centreline.
        y_abs = y_centre + y_ts

        U_target, TI_target = extract_pywake_yz_fields(
            sim_res=sim_res,
            x_probe=x_probe,
            y_abs=y_abs,
            z_abs=z_ts,
        )
        
        if config.plot_sampled_field and seed == config.seeds[0]:
            plot_pywake_sampled_plane(
                sim_res=sim_res,
                x_probe=x_probe,
                y_centre=y_centre,
                y_ts=y_ts,
                z_ts=z_ts,
                hub_height=config.hub_height,
                rotor_diameter=config.rotor_diameter,
                title=f"{model_name}: rotor-specific PyWake sample, seed {seed}",
            )

        ts = superimpose_target_fields_on_turbsim(
            ts=ts,
            U_target=U_target,
            TI_target=TI_target,
            avoid_reducing_ti=config.avoid_reducing_ti,
        )

        out_file = out_dir / f"15MW_U10_S{seed}_{model_name}_waked.bts"
        ts.write(str(out_file))
        print(f"Saved: {out_file}")


# =============================================================================
# OPTIONAL FIELD PLOTTING
# =============================================================================

def plot_target_field(
    U_target: np.ndarray,
    TI_target: np.ndarray,
    y: np.ndarray,
    z: np.ndarray,
    title: str,
) -> None:
    """Plot sampled PyWake fields on the TurbSim grid for checking."""

    fig, ax = plt.subplots(1, 2, figsize=(11, 4))

    c0 = ax[0].contourf(y, z, U_target.T, levels=30)
    fig.colorbar(c0, ax=ax[0], label="U [m/s]")
    ax[0].set_title("Mean velocity")

    c1 = ax[1].contourf(y, z, TI_target.T, levels=30)
    fig.colorbar(c1, ax=ax[1], label="TI [-]")
    ax[1].set_title("Turbulence intensity")

    for axis in ax:
        axis.set_xlabel("y [m]")
        axis.set_ylabel("z [m]")

    fig.suptitle(title)
    fig.tight_layout()
    plt.show()


# =============================================================================
# MAIN WORKFLOW
# =============================================================================

def main() -> None:
    """Run the PyWake-to-TurbSim superposition workflow."""

    config = WorkflowConfig()

    D = config.rotor_diameter

    x, y = build_rotated_grid_layout(
        n_rows=config.n_rows,
        n_cols=config.n_cols,
        spacing_x_m=config.streamwise_spacing_D * D,
        spacing_y_m=config.crossflow_spacing_D * D,
        rotation_deg=config.farm_rotation_deg,
    )

    if config.plot_layout:
        plot_farm_layout(
            x,
            y,
            title=(
                f"{config.n_rows} x {config.n_cols} wind farm, "
                f"{config.streamwise_spacing_D:g}D spacing, "
                f"hub height {config.hub_height:g} m"
            ),
        )

    turbine_index = config.turbine_number - 1
    if turbine_index < 0 or turbine_index >= len(x):
        raise IndexError(
            f"turbine_number={config.turbine_number} is outside the farm layout "
            f"range 1-{len(x)}."
        )

    x_centre = x[turbine_index]
    y_centre = y[turbine_index]
    x_probe = x_centre - config.upstream_sampling_distance_D * D

    print(f"Selected turbine: T{config.turbine_number}")
    print(f"Rotor diameter = {config.rotor_diameter:g} m")
    print(f"Hub height     = {config.hub_height:g} m")
    print(f"Sampling plane: {config.upstream_sampling_distance_D:g}D upstream")
    print(f"x_probe = {x_probe:.3f} m")

    # Wake-model construction still uses setup_wind_farm_model from custom_functions.py.
    # The turbine/site are defined here so the PyWake setup matches the original
    # 15 MW / 240 m / 150 m workflow and includes power-law shear.
    wind_turbines = create_iea_15mw_wind_turbines()
    site = create_pywake_site(
        ambient_wind_speed=config.ambient_wind_speed,
        ambient_ti=config.ambient_ti,
        hub_height=config.hub_height,
        shear_alpha=config.shear_alpha,
    )

    simulation_outputs = run_pywake_models(
        model_names=config.models,
        site=site,
        wind_turbines=wind_turbines,
        x=x,
        y=y,
        wind_direction_deg=config.wind_direction_deg,
        wind_speed=config.ambient_wind_speed,
    )

    for model_name, sim_res in simulation_outputs.items():
        if config.plot_full_pywake_plane:
            plot_full_pywake_yz_plane(
                sim_res=sim_res,
                x_probe=x_probe,
                y_centre=y_centre,
                x_layout=x,
                y_layout=y,
                target_index=turbine_index,
                rotor_diameter=config.rotor_diameter,
                hub_height=config.hub_height,
                model_name=model_name,
                turbine_number=config.turbine_number,
            )

        write_pywake_superposed_bts(
            config=config,
            sim_res=sim_res,
            model_name=model_name,
            x_probe=x_probe,
            y_centre=y_centre,
        )


if __name__ == "__main__":
    main()


# %%
